version: '3.7'

services:
  myapp:
    restart: always
    image: "${MYAPP_REGISTERY}"
    environment:
       - VIRTUAL_HOST=${MYAPP_HOST}
       - VIRTUAL_PORT=80
    expose:
       - 80
    networks:
       - development

networks:
  development:
    name: "development_network"
